### ISSUE TITLE
[Feature request] Automatically open cleaned URL in browser for selected sanitizers

### ISSUE THREAD

**Issue by xanoni** [svenjacobs/leon#143]
For each sanitizer, the user should be able to select whether he/she wants the Leon activity/window to open (current behavior) vs. Leon just directly opening the URL in the user's preferred browser (without further confirmation / button presses).

Why? For certain types of links that I click frequently, the manual steps ("Share -> Select Browser app from list") seem inefficient.

This would be especially useful when Leon is set as the Android-wide default browser for all links.

**Comment by svenjacobs** [comment]
Hello @xanoni, thanks for your feedback.
I see a few problems with this request:

First, not all sanitizers operate only on specific domains. For instance the Google Analytics (`ga_*`) or Facebook (`fb_*`) sanitizers remove tracking parameters on all domains. What should happen if a URL contains both types of parameters and a different browser is set for Google and Facebook sanitizers, say Google opens Chrome and Facebook Firefox?

Second, if Leon is set as the default browser it cannot automatically open a link in the default browser because that would be Leon and we would have an endless loop 😉 So either Leon always has to display the intent chooser dialog or we need to introduce a configuration option to specify the "default" browser used by Leon.

**Comment by xanoni** [comment]
**Re/ your 1st point:** I didn't know/realize this. I guess you would always have to show the activity if one of those sanitizers got triggered.

**Re/ your 2nd point:** I realized this before I posted, but wanted to get a discussion started at least :-) Yes, I agree that the user would then have to define their default browser in the app settings. This could be global or on a per-sanitizer basis.

By the way, do you know [URLCheck](https://f-droid.org/en/packages/com.trianguloy.urlchecker/)? They show you a dropdown with all your installed browsers in their popup activity, and it remembers the most recently selected one. Much easier than pressing "Share" and then trying to find your browser in a long list of mostly irrelevant apps.

**Comment by xanoni** [comment]
@svenjacobs cool, it works. Only issue I noticed is that when using the "dark" Android theme, the "Action after clean" dropdown is black font color on almost black background. Can't see what you've selected.

**Comment by svenjacobs** [comment]
@xanoni 

> Only issue I noticed is that when using the "dark" Android theme, the "Action after clean" dropdown is black font color on almost black background. Can't see what you've selected.

That's weird. I assumed that the drop down uses the correct colors in dark mode. I created a new [issue](https://github.com/svenjacobs/leon/issues/182).

**Comment by svenjacobs** [comment]
@all-contributors please add @xanoni for bug ideas
