### ISSUE TITLE
Leon not showing all the installed browsers

### ISSUE THREAD

**Issue by esemismo22** [svenjacobs/leon#152]
I have noticed that with Leon, contrary to other apps, such as URLCheck, both downloaded from f-droid, there is at least one browser that does not turn up in the share menu. It is smartcookie web. The weird thing is it does appear as an available browser in any other share menu but that of Leon. 

Maybe it is not worth going into it since it is not widely used, and probably discontinued, but it can be due to some issue that could happen also with other apps.

This is my current device, although I also noticed it in previous ones whose configuration I can not remember:

Oppo A16s
Android 12 (ColorOS V12.1)

**Comment by svenjacobs** [comment]
Hello @esemismo22, thanks for your feedback.

The **Share** button is meant to share the result via for example an instant messenger and not to open a browser. Hence an intent with action [ACTION_VIEW](https://developer.android.com/reference/android/content/Intent#ACTION_VIEW) and MIME type `text/plain` is send to the system. I guess it's pure luck that some browsers are listed in the share dialog because any application that can handle text should be displayed here.

Please mind that the result cannot just be a plain URL but also something like

```
I just found this show on Netflix

https://www.netflix.com/...
```

To actually open a browser or presenting a list of available browsers, I would have to send an intent with [ACTION_SEND](https://developer.android.com/reference/android/content/Intent#ACTION_SEND) and set the URI as the [data](https://developer.android.com/reference/android/content/Intent#setData(android.net.Uri)) property.

Since this is a completely different type of intent, what I could do is adding a new **Open** button to the main screen of Leon. Would that be okay for you?

**Comment by esemismo22** [comment]
Of course, that would do, while including an extra feature that I am sure will be useful to most users.

Thanks for your response and congratulations for your great job.

Carlos

1 feb 2023 11:02:58 Sven Jacobs ***@***.***>:

**Comment by esemismo22** [comment]
Another good choice to add would be the possibility of using (sharing, opening, copying, etc.) the original URL without cleaning anything. Sometimes, the parameters that get removed are necessary for the link to work properly. Of course, you may not send the link to the app to achieve this, but this way you can use Leon as the default browser of choice, which adds an extra security step since it filters the URLs and prevents them from directly open in case of accidentally pressing a link.

**Comment by svenjacobs** [comment]
> Another good choice to add would be the possibility of using (sharing, opening, copying, etc.) the original URL without cleaning anything. Sometimes, the parameters that get removed are necessary for the link to work properly.

I don't think this would make sense since this is basically the job of Leon, to remove obsolete parameters. If you find links that stop working after Leon cleaned them, please report this as a bug. Because actually all the removed parameters should not be relevant for proper functionality of a site.

**Comment by esemismo22** [comment]
Cool! I am sure that will be of use to other users as well.

Thanks for your great job.

**Comment by svenjacobs** [comment]
@all-contributors please add @esemismo22 for ideas
