### ISSUE TITLE
[Feature Request] Add option to auto re-share

### ISSUE THREAD

**Issue by felixschndr** [svenjacobs/leon#169]
Hey there =)

I'd love to see a toggle in the settings which enables the following behaviour:

Current:
1. Share a link in an app (i.e. amazon)
2. Select URL Shortener
3. URL Shortener is opened
4. Click in "share" to open the share menu to re-share to i.e. whatsapp

New feature:
1. Share a link in an app (i.e. amazon)
2. Select URL Shortener
3. The share menu is automatically opened again. Thus the user doesn't have to click "share" in the app and can directly send the link to the desired contact. This reduces the _overhead_ provided by an URL shortener by 1 click, doesn't sound much, but that's 1/2 of all necessary clicks.

In this case the UI of the App (the actual opening of the screen of the app) might be skipped to. Thus leading to:
1. Share a link in an app (i.e. amazon)
2. Select URL Shortener
3. Select whatsapp, select contact and send
4. Press Back --> go to amazon and not the app

---

I'd be happy to test if a tester is wanted

**Comment by svenjacobs** [comment]
Hello Felix,

thanks for your feature request. That sounds like a useful feature 😃 I see similarities to #71 where also some automatic action after cleaning is desired. Similar to #71 we would also probably have to provide a second app icon (a second `Activity`), which when used when sending a link to Leon, automatically opens the share dialog afterwards.

**Comment by felixschndr** [comment]
> Similar to https://github.com/svenjacobs/leon/issues/71 we would also probably have to provide a second app icon (a second Activity), which when used when sending a link to Leon, automatically opens the share dialog afterwards.

I am wondering if it is necessary to add a seconds app icon to the share menu. Share menus are cluttered enough these days (in my opinion). I'd suggest the following behaviour (\*1):
- If the app is opened _normally_ (i.e. from an appdrawer) the normal UI opens
- If the app is opened via the share menu the above mentioned behavior happens (--> automatically a new share dialog is opened)

This would negate the necessity for a second app icon. What do you think about this?

----

\*1: Based on the assumption that in code you can disgingiish between the two cases

**Comment by svenjacobs** [comment]
It is possible to distinguish between a normal open and open via share menu, however Leon was designed to be primarily used from the share menu. The possibility to read an URL from the clipboard when Leon was open normally, was actually added to the app later.

So if we change the default behaviour by automatically opening the share menu with the cleaned URL, users that don't want this behaviour because the want to use another functionality of Leon, like verifying the link or copying it to the clipboard, now need to perform the following cumbersome steps:

1. Copy the to be cleaned URL into the clipboard
2. Open Leon normally
3. Import from clipboard
4. Select desired action

That is why I proposed to add another app icon. What we could also do is introduce a new option in the settings (`Open share menu automatically`) which can be enabled if desired. That would not require another app icon.

**Comment by felixschndr** [comment]
>  What we could also do is introduce a new option in the settings (Open share menu automatically) which can be enabled if desired. That would not require another app icon.

This is what a suggested in my original post^^:
> I'd love to see a toggle in the settings which enables the following behavior

And I think this would be the better option

**Comment by svenjacobs** [comment]
This has been implemented in #172 and will be available in v25.

**Comment by svenjacobs** [comment]
@all-contributors please add @felixschndr for ideas

**Comment by felixschndr** [comment]
@svenjacobs thank you very much!
