### ISSUE TITLE
[Feature Request] Clean Reddit Links

### ISSUE THREAD

**Issue by swifter78neo** [svenjacobs/leon#170]
Hello! I was wondering if reddit links can be supported in URL Cleaner? usually upon sharing from the app, the link is appended with such info: "utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button".

Thanks!

**Comment by svenjacobs** [comment]
Hello @swifter78neo, thanks for your feedback.

`utm_*` parameters are coming from Google Analytics and should actually already be removed by the [GoogleAnalyticsSanitizer](https://github.com/svenjacobs/leon/blob/7b19a7e02872d22b7b980b4df662c875650e81be/core-domain/src/main/kotlin/com/svenjacobs/app/leon/core/domain/sanitizer/google/GoogleAnalyticsSanitizer.kt).

Does it not work? 🤔

**Comment by TPS** [comment]
> Does it not work? 🤔

I think no, for the original case (I don't see GLytics parameters, though, maybe due to my setup? 🤷🏾‍♂️) like

`https://out.reddit.com/t3_11zcpau?url=https%3A%2F%2Fcompress-or-die.com%2FThe-nasty-red-JPG-compression-artifacts&token=AQAA-odsZCyQ04Ae10crjvg8DGlsTPckMpu3vvIjNwmWPgLdQMbC&app_name=web2x&web_redirect=true/`

which should be decoded/stripped to just

`https://compress-or-die.com/The-nasty-red-JPG-compression-artifacts`

---

Some background for a related case in https://github.com/AdguardTeam/cname-trackers/issues/68.  In a nutshell, click.Reddit links from e-mail notifications don't work right, either.  E.g.,

`https://click.redditmail.com/CL0/https:%2F%2Fwww.reddit.com%2Fr%2FCompressOrDie%2Fcomments%2F11u2vso%2Frcompressordie_lounge%2Fjl9fp68%2F%3F$deep_link=true%26correlation_id=5329d6c9-34a4-4a44-9cea-76317f68123f%26ref=email_comment_reply%26ref_campaign=email_comment_reply%26ref_source=email/3/010001884768a910-4b97a265-36d8-461f-9d79-fc2b535e5217-000000/sa_uFF6uMCdJu1cTLCaOI8Ng6wQBjfPtc5hMCnOrx4Q=301`

should be decoded/stripped to just

`https://www.reddit.com/r/CompressOrDie/comments/11u2vso/comment/jl9fp68/`

**Comment by svenjacobs** [comment]
@TPS 

> I think no, for the original case...

Well, I was referring to @swifter78neo comment where they only mentioned `utm_*` parameters 😉 

Can you please summarize what Reddit links there are and how they should be cleaned? So we have `out.reddit.com` and `click.redditmail.com`? Anything else?

**Comment by TPS** [comment]
I've not run into any others, but I'm a Reddit utter novice.  Maybe @swifter78neo or @amano-kenji (from the linked issue) would know of more?

**Comment by amano-kenji** [comment]
@TPS You figured it out already.

**Comment by svenjacobs** [comment]
@TPS The two sanitizers have been added with #195.

Just to be clear: The decoded and cleaned URL from your `out.redditmail.com` example above is 

```
https://www.reddit.com/r/CompressOrDie/comments/11u2vso/rcompressordie_lounge/jl9fp68/
```

not

```
https://www.reddit.com/r/CompressOrDie/comments/11u2vso/comment/jl9fp68/
```

However the first URL redirects to the second when opened.
