### ISSUE TITLE
Leon doesn't remove the referral code 

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#298]
Maybe this might be optional (in some cases the referral code is useful).
Might you adding a referral code ON/OFF switch?
All the switches have to remember the previously choise made when I launch Leon next times.

(Leon) With referral:
https://app.aave.com/?referral=93

Without referral, modified manually by me:
https://app.aave.com/

![1000093000](https://github.com/svenjacobs/leon/assets/113377431/f6bc8b49-7cf9-4d02-b59e-0c91867bc72a)

**Comment by svenjacobs** [comment]
Hm, this is a very specific use case. I really don't want to overload Leon with functionality that isn't used often. I think if the result would be [editable](https://github.com/svenjacobs/leon/issues/189), you could remove the referral yourself? There I'm closing this issue because #189 should solve this.

**Comment by svenjacobs** [comment]
No, but it doesn't make sense to have to issues open for the same feature :)
