### ISSUE TITLE
Integrate Leon into system context menu for text

### ISSUE THREAD

**Issue by NikunjKhangwal** [svenjacobs/leon#386]
Maybe something like this?
![IMG_20240330_133046](https://github.com/svenjacobs/leon/assets/99175083/ad11bdab-572f-4821-8220-54ab67c40bdd)

I think it would be easier to use if we can stay in the current app and perform actions through a pop-up window instead of switching to Leon

**Comment by svenjacobs** [comment]
Hello, this is from [Untracker](https://github.com/zhanghai/Untracker), right? It seems they use Intent [android.intent.action.PROCESS_TEXT](https://developer.android.com/reference/android/content/Intent.html#ACTION_PROCESS_TEXT) to integrate into the System context menu for text.

Of course I could do the same for Leon but since this is a system UI, Leon could only clean URLs with the default sanitizers and settings since it's not possible to display any custom UI in this sheet.

**Comment by NikunjKhangwal** [comment]
That's totally fine. Something is better than nothing

**Comment by svenjacobs** [comment]
This has been implemented and will be available in the next release.

**Comment by NikunjKhangwal** [comment]
Thanks a lot

**Comment by svenjacobs** [comment]
@all-contributors please add @NikunjKhangwal for ideas
