### ISSUE TITLE
v1.0.0 failed building on F-Droid

### ISSUE THREAD

**Issue by TPS** [svenjacobs/leon#53]
@svenjacobs Here's the [build log](https://github.com/svenjacobs/leon/files/9172995/com.svenjacobs.app.leon_234.log.gz).

**Comment by svenjacobs** [comment]
Thanks for pointing this out. The problem seems to be

> No hash for gradle version 7.5! Exiting...

This type of error seems to occur [now and then](https://forum.f-droid.org/t/f-droid-cannot-build-apps-because-no-hash-for-gradle-version-7-0-x/13690) when the hashes of new Gradle versions are not yet updated on F-Droid. The hash for Gradle 7.5 was [added one week ago](https://gitlab.com/fdroid/fdroidserver/-/commit/848e29294c50b257f7411cc11626f3a4b0e5a2dc) but it seems the build server was not up-to-date when it ran the build for Leon 1.0.0.

**Comment by svenjacobs** [comment]
Need [feedback](https://forum.f-droid.org/t/build-error-no-hash-for-gradle-version-7-5/19111) from the F-Droid community.

**Comment by svenjacobs** [comment]
Apparently we just have to wait until F-Droid retries the build.

**Comment by svenjacobs** [comment]
Just an update: Builds on F-Droid still fail because the build server is not yet updated with the latest Gradle hashes. The responsible person [was notified](https://forum.f-droid.org/t/build-error-no-hash-for-gradle-version-7-5/19111/6).

**Comment by svenjacobs** [comment]
The build went through! 🎉  1.0.0 should be available on F-Droid soon.

**Comment by TPS** [comment]
Build has finally come to the repo.
