### ISSUE TITLE
App doesn't decode amazon links

### ISSUE THREAD

**Issue by aha999** [svenjacobs/leon#75]
The link that i shared: https://a.co/d/4X8EKfk

After i select decode link, it doesn't decode it into a raw form: https://www.amazon.com/dp/B09FDSW9CS/

**Comment by svenjacobs** [comment]
Hello Klemen,

the [decode switch](https://github.com/svenjacobs/leon/issues/49) means decoding a [URL encoded](https://en.wikipedia.org/wiki/Percent-encoding) link, not decoding a short link into its long form.

Regarding the Amazon short link, it doesn't seem to be as simple as with [youtu.be](https://github.com/svenjacobs/leon/issues/56) links for example because the short link itself doesn't contain all the information required to build the full link out of it. Only Amazon knows the full link behind `4X8EKfk` so Leon would have to do a HTTP request to unwrap the link. I'm not sure how I feel about this because currently Leon can do all the cleaning and unwrapping locally without the need for Internet access. It currently doesn't even need the [Internet permission](https://developer.android.com/reference/android/Manifest.permission#INTERNET).

**Comment by svenjacobs** [comment]
Let's just assume we would want to unwrap Amazon short links via HTTP requests. This would mean that Leon 

- needs a progress dialog / screen after a link was send to Leon and before the result is displayed, because HTTP requests might take a few seconds
- needs to handle possible errors of HTTP requests
- needs some kind of prioritization for sanitizer rules because unwrapping should happen before other rules are applied

**Comment by aha999** [comment]
Then unwrapping links is what i meant. this would be great because then it could remove the tracking from such links

**Comment by svenjacobs** [comment]
I decided to **not** implement this because I believe that Leon should stay close to its roots, namely providing privacy by removing tracking and other obsolete parameters. Performing network requests reduces privacy because it

**Comment by svenjacobs** [comment]
I decided to **not** implement this because I believe that Leon should stay close to its roots, namely providing privacy by removing tracking and other obsolete parameters. Performing network requests actually **reduces** privacy because it leaves trails on the server owned by the company, in this case Amazon. If you really want to sanitize these URLs, please unwrap them manually by opening them and then send the unwrapped URL to Leon. If you further want to talk about this, please use [this](https://github.com/svenjacobs/leon/discussions/80) discussion.
