### ISSUE TITLE
AliExpress

### ISSUE THREAD

**Issue by guerda** [svenjacobs/leon#91]
AliExpress has a lot of tracking parameters ok the URL. 

    https://m.de.aliexpress.com/item/32948511896.html?ug_edm_item_id=32948511896&pdp_npi=2%40dis%21EUR%21%E2%82%AC%2024%2C58%21%E2%82%AC%2014%2C50%21%21%21%21%21%402102fea916677108936606992d1f0c%2112000027801501608%21edm&edm_click_module=item_detail&tracelog=rowan&rowan_id1=aeug_edm_24677_1_de_DE_2022-11-05&rowan_msg_id=8681biz_pay_after_purchase%3A0%3A0_572584174%248a93ce02da764ff48f65112ca837f7df&ck=in_edm_other&gatewayAdapt=gloPc2deuMsite

But it needs only

    https://m.de.aliexpress.com/item/32948511896.html

**Comment by svenjacobs** [comment]
Hello @guerda,

thanks for your feedback. If you have a bit of Android / Kotlin development knowledge, a pull request would be very welcome 😄 Since all parameters need to be removed, it should be very similar to [EbaySanitizer](https://github.com/svenjacobs/leon/blob/05a4423cc64255579035e2377ec503b74b2cd8f2/app/src/main/kotlin/com/svenjacobs/app/leon/sanitizer/ebay/EbaySanitizer.kt) for example.

**Comment by guerda** [comment]
I'll try!
